// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAalzK318Fz94Mh9RMlnq2r9VPpYoBL6g',
    appId: '1:690920929191:web:9c41601da760220b10a882',
    messagingSenderId: '690920929191',
    projectId: 'splitify-a0dee',
    authDomain: 'splitify-a0dee.firebaseapp.com',
    storageBucket: 'splitify-a0dee.appspot.com',
    measurementId: 'G-0NE0HRWL4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZAK2RJ3P4rRq-x0OjGG8Ee_GHRfo7U4',
    appId: '1:690920929191:android:085f66b2f5490f3010a882',
    messagingSenderId: '690920929191',
    projectId: 'splitify-a0dee',
    storageBucket: 'splitify-a0dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6MgX0icysZhYVtCvWqhJ4FHSlHWfc7yA',
    appId: '1:690920929191:ios:8fb378032abdb96f10a882',
    messagingSenderId: '690920929191',
    projectId: 'splitify-a0dee',
    storageBucket: 'splitify-a0dee.appspot.com',
    iosBundleId: 'com.example.splitify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6MgX0icysZhYVtCvWqhJ4FHSlHWfc7yA',
    appId: '1:690920929191:ios:8755fe1699eba41210a882',
    messagingSenderId: '690920929191',
    projectId: 'splitify-a0dee',
    storageBucket: 'splitify-a0dee.appspot.com',
    iosBundleId: 'com.example.splitify.RunnerTests',
  );
}
